import type { SchoolConfig } from "./types";

/**
 * Default school configuration with all 30 subjects.
 * This matches the original index.html calculator exactly.
 * Used as a fallback when no database is available.
 */
export const DEFAULT_SCHOOL_CONFIG: SchoolConfig = {
  id: "default",
  name: 'משחוק מצויינות מנכ"ל תשפ"ו',
  slug: "default",
  categories: [
    {
      id: "core",
      name: "מקצועות חובה",
      icon: "\u{1F4DA}",
      sortOrder: 0,
      subjects: [
        {
          id: "math",
          name: "מתמטיקה",
          categoryId: "core",
          units: 0,
          hasLevels: true,
          levels: [
            {
              id: "4",
              label: '4 יח"ל',
              units: 4,
              sortOrder: 0,
              components: [
                { id: "math_4_a", name: "שאלון 35481", weight: 0.65, sortOrder: 0 },
                { id: "math_4_b", name: "שאלון 35482", weight: 0.35, sortOrder: 1 },
              ],
            },
            {
              id: "5",
              label: '5 יח"ל',
              units: 5,
              sortOrder: 1,
              components: [
                { id: "math_5_a", name: "שאלון 35581", weight: 0.60, sortOrder: 0 },
                { id: "math_5_b", name: "שאלון 35582", weight: 0.40, sortOrder: 1 },
              ],
            },
          ],
          components: [],
          dependsOnId: null,
          depLabel: null,
          depWeight: null,
          sortOrder: 0,
        },
        {
          id: "english",
          name: "אנגלית",
          categoryId: "core",
          units: 5,
          hasLevels: false,
          levels: [],
          components: [
            { id: "e", name: "שאלון E - 16481", weight: 0.27, sortOrder: 0 },
            { id: "f", name: "שאלון F - 16583", weight: 0.26, sortOrder: 1 },
            { id: "g", name: "שאלון G - 16582", weight: 0.27, sortOrder: 2 },
            { id: "oral", name: "בעל פה", weight: 0.20, sortOrder: 3 },
          ],
          dependsOnId: null,
          depLabel: null,
          depWeight: null,
          sortOrder: 1,
        },
        {
          id: "history",
          name: "היסטוריה",
          categoryId: "core",
          units: 2,
          hasLevels: false,
          levels: [],
          components: [
            { id: "a", name: "פנימי", weight: 0.30, sortOrder: 0 },
            { id: "b", name: "חיצוני", weight: 0.70, sortOrder: 1 },
          ],
          dependsOnId: null,
          depLabel: null,
          depWeight: null,
          sortOrder: 2,
        },
        {
          id: "literature",
          name: "ספרות",
          categoryId: "core",
          units: 2,
          hasLevels: false,
          levels: [],
          components: [
            { id: "a", name: "פנימי", weight: 0.30, sortOrder: 0 },
            { id: "b", name: "חיצוני", weight: 0.70, sortOrder: 1 },
          ],
          dependsOnId: null,
          depLabel: null,
          depWeight: null,
          sortOrder: 3,
        },
        {
          id: "tanach",
          name: 'תנ"ך',
          categoryId: "core",
          units: 2,
          hasLevels: false,
          levels: [],
          components: [
            { id: "a", name: "פנימי", weight: 0.30, sortOrder: 0 },
            { id: "b", name: "חיצוני", weight: 0.70, sortOrder: 1 },
          ],
          dependsOnId: null,
          depLabel: null,
          depWeight: null,
          sortOrder: 4,
        },
        {
          id: "civics",
          name: "אזרחות",
          categoryId: "core",
          units: 2,
          hasLevels: false,
          levels: [],
          components: [
            { id: "a", name: "פנימי", weight: 0.20, sortOrder: 0 },
            { id: "b", name: "חיצוני", weight: 0.80, sortOrder: 1 },
          ],
          dependsOnId: null,
          depLabel: null,
          depWeight: null,
          sortOrder: 5,
        },
        {
          id: "language",
          name: "לשון",
          categoryId: "core",
          units: 2,
          hasLevels: false,
          levels: [],
          components: [
            { id: "a", name: "פנימי", weight: 0.30, sortOrder: 0 },
            { id: "b", name: "חיצוני", weight: 0.70, sortOrder: 1 },
          ],
          dependsOnId: null,
          depLabel: null,
          depWeight: null,
          sortOrder: 6,
        },
      ],
    },
    {
      id: "science",
      name: "מדעים וטכנולוגיה",
      icon: "\u{1F52C}",
      sortOrder: 1,
      subjects: [
        {
          id: "physics",
          name: "פיזיקה",
          categoryId: "science",
          units: 5,
          hasLevels: false,
          levels: [],
          components: [
            { id: "int", name: "פנימי", weight: 0.30, sortOrder: 0 },
            { id: "mech", name: "מכניקה חיצוני", weight: 0.30, sortOrder: 1 },
            { id: "elec", name: "חשמל חיצוני", weight: 0.25, sortOrder: 2 },
            { id: "lab", name: "מעבדה חיצוני", weight: 0.15, sortOrder: 3 },
          ],
          dependsOnId: null,
          depLabel: null,
          depWeight: null,
          sortOrder: 0,
        },
        {
          id: "biology",
          name: "ביולוגיה",
          categoryId: "science",
          units: 5,
          hasLevels: false,
          levels: [],
          components: [
            { id: "int", name: "פנימי", weight: 0.30, sortOrder: 0 },
            { id: "ext", name: "בחינה חיצונית", weight: 0.55, sortOrder: 1 },
            { id: "lab", name: "מעבדה חיצונית", weight: 0.15, sortOrder: 2 },
          ],
          dependsOnId: null,
          depLabel: null,
          depWeight: null,
          sortOrder: 1,
        },
        {
          id: "chemistry",
          name: "כימיה",
          categoryId: "science",
          units: 5,
          hasLevels: false,
          levels: [],
          components: [
            { id: "res", name: "עבודת חקר", weight: 0.30, sortOrder: 0 },
            { id: "ext", name: "בחינה חיצונית", weight: 0.55, sortOrder: 1 },
            { id: "oral", name: "בעל פה חיצוני", weight: 0.15, sortOrder: 2 },
          ],
          dependsOnId: null,
          depLabel: null,
          depWeight: null,
          sortOrder: 2,
        },
        {
          id: "cs",
          name: "מדעי המחשב",
          categoryId: "science",
          units: 5,
          hasLevels: false,
          levels: [],
          components: [
            { id: "int", name: "פנימי", weight: 0.24, sortOrder: 0 },
            { id: "ext1", name: "בחינה חיצונית א'", weight: 0.36, sortOrder: 1 },
            { id: "ext2", name: "בחינה חיצונית ב'", weight: 0.40, sortOrder: 2 },
          ],
          dependsOnId: null,
          depLabel: null,
          depWeight: null,
          sortOrder: 3,
        },
        {
          id: "medicine",
          name: "מדעי הרפואה",
          categoryId: "science",
          units: 5,
          hasLevels: false,
          levels: [],
          components: [
            { id: "int", name: "פנימי", weight: 0.30, sortOrder: 0 },
            { id: "ext", name: "בחינה חיצונית", weight: 0.70, sortOrder: 1 },
          ],
          dependsOnId: null,
          depLabel: null,
          depWeight: null,
          sortOrder: 4,
        },
        {
          id: "medicine_thesis",
          name: "מדעי הרפואה - עבודת גמר",
          categoryId: "science",
          units: 5,
          hasLevels: false,
          levels: [],
          components: [
            { id: "proj", name: "פרויקט גמר", weight: 1.0, sortOrder: 0 },
          ],
          dependsOnId: null,
          depLabel: null,
          depWeight: null,
          sortOrder: 5,
        },
        {
          id: "data_info",
          name: "מידע ונתונים",
          categoryId: "science",
          units: 5,
          hasLevels: false,
          levels: [],
          components: [
            { id: "int", name: "פנימי", weight: 0.30, sortOrder: 0 },
            { id: "ext", name: "בחינה חיצונית", weight: 0.70, sortOrder: 1 },
          ],
          dependsOnId: null,
          depLabel: null,
          depWeight: null,
          sortOrder: 6,
        },
      ],
    },
    {
      id: "social",
      name: "חברה ורוח",
      icon: "\u{1F30D}",
      sortOrder: 2,
      subjects: [
        {
          id: "social",
          name: "מדעי החברה",
          categoryId: "social",
          units: 5,
          hasLevels: false,
          levels: [],
          components: [
            { id: "psy1", name: "פסיכולוגיה א'", weight: 0.12, sortOrder: 0 },
            { id: "psy2", name: "פסיכולוגיה ב'", weight: 0.28, sortOrder: 1 },
            { id: "methods", name: "שיטות מחקר", weight: 0.20, sortOrder: 2 },
            { id: "socio", name: "סוציולוגיה", weight: 0.40, sortOrder: 3 },
          ],
          dependsOnId: null,
          depLabel: null,
          depWeight: null,
          sortOrder: 0,
        },
        {
          id: "management",
          name: "מנהל וכלכלה",
          categoryId: "social",
          units: 5,
          hasLevels: false,
          levels: [],
          components: [
            { id: "int", name: "פנימי", weight: 0.30, sortOrder: 0 },
            { id: "ext", name: "בחינה חיצונית", weight: 0.70, sortOrder: 1 },
          ],
          dependsOnId: null,
          depLabel: null,
          depWeight: null,
          sortOrder: 1,
        },
        {
          id: "geography",
          name: "גאוגרפיה",
          categoryId: "social",
          units: 5,
          hasLevels: false,
          levels: [],
          components: [
            { id: "int", name: "פנימי", weight: 0.40, sortOrder: 0 },
            { id: "ext", name: "בחינה חיצונית", weight: 0.60, sortOrder: 1 },
          ],
          dependsOnId: null,
          depLabel: null,
          depWeight: null,
          sortOrder: 2,
        },
      ],
    },
    {
      id: "extended",
      name: "הרחבות",
      icon: "\u{1F4D6}",
      sortOrder: 3,
      subjects: [
        {
          id: "tanach_ext",
          name: 'תנ"ך מורחב',
          categoryId: "extended",
          units: 5,
          hasLevels: false,
          levels: [],
          components: [
            { id: "int", name: "פנימי", weight: 0.18, sortOrder: 0 },
            { id: "ext", name: "חיצוני", weight: 0.42, sortOrder: 1 },
          ],
          dependsOnId: "tanach",
          depLabel: 'ציון תנ"ך בסיסי',
          depWeight: 0.40,
          sortOrder: 0,
        },
        {
          id: "civics_ext",
          name: "אזרחות מורחב",
          categoryId: "extended",
          units: 5,
          hasLevels: false,
          levels: [],
          components: [
            { id: "int", name: "פנימי", weight: 0.18, sortOrder: 0 },
            { id: "ext", name: "חיצוני", weight: 0.42, sortOrder: 1 },
          ],
          dependsOnId: "civics",
          depLabel: "ציון אזרחות בסיסי",
          depWeight: 0.40,
          sortOrder: 1,
        },
      ],
    },
    {
      id: "lang",
      name: "שפות",
      icon: "\u{1F5E3}\uFE0F",
      sortOrder: 4,
      subjects: [
        {
          id: "chinese",
          name: "סינית",
          categoryId: "lang",
          units: 5,
          hasLevels: false,
          levels: [],
          components: [
            { id: "int", name: "פנימי", weight: 0.40, sortOrder: 0 },
            { id: "ext", name: "בחינה חיצונית", weight: 0.60, sortOrder: 1 },
          ],
          dependsOnId: null,
          depLabel: null,
          depWeight: null,
          sortOrder: 0,
        },
        {
          id: "spanish",
          name: "ספרדית",
          categoryId: "lang",
          units: 5,
          hasLevels: false,
          levels: [],
          components: [
            { id: "int", name: "פנימי", weight: 0.40, sortOrder: 0 },
            { id: "ext", name: "בחינה חיצונית", weight: 0.60, sortOrder: 1 },
          ],
          dependsOnId: null,
          depLabel: null,
          depWeight: null,
          sortOrder: 1,
        },
        {
          id: "french",
          name: "צרפתית",
          categoryId: "lang",
          units: 5,
          hasLevels: false,
          levels: [],
          components: [
            { id: "int", name: "פנימי", weight: 0.30, sortOrder: 0 },
            { id: "ext", name: "בחינה חיצונית", weight: 0.70, sortOrder: 1 },
          ],
          dependsOnId: null,
          depLabel: null,
          depWeight: null,
          sortOrder: 2,
        },
        {
          id: "arabic",
          name: "ערבית",
          categoryId: "lang",
          units: 5,
          hasLevels: false,
          levels: [],
          components: [
            { id: "a", name: "כתוב", weight: 0.50, sortOrder: 0 },
            { id: "oral", name: "בעל פה", weight: 0.20, sortOrder: 1 },
            { id: "b", name: "חיצוני", weight: 0.30, sortOrder: 2 },
          ],
          dependsOnId: null,
          depLabel: null,
          depWeight: null,
          sortOrder: 3,
        },
      ],
    },
    {
      id: "arts",
      name: "אמנויות",
      icon: "\u{1F3A8}",
      sortOrder: 5,
      subjects: [
        {
          id: "dance",
          name: "מחול",
          categoryId: "arts",
          units: 5,
          hasLevels: false,
          levels: [],
          components: [
            { id: "int", name: "פנימי", weight: 0.50, sortOrder: 0 },
            { id: "ext", name: "בחינה חיצונית", weight: 0.50, sortOrder: 1 },
          ],
          dependsOnId: null,
          depLabel: null,
          depWeight: null,
          sortOrder: 0,
        },
        {
          id: "theater",
          name: "תאטרון",
          categoryId: "arts",
          units: 5,
          hasLevels: false,
          levels: [],
          components: [
            { id: "int", name: "פנימי", weight: 0.50, sortOrder: 0 },
            { id: "ext", name: "בחינה חיצונית", weight: 0.50, sortOrder: 1 },
          ],
          dependsOnId: null,
          depLabel: null,
          depWeight: null,
          sortOrder: 1,
        },
        {
          id: "music",
          name: "מוזיקה",
          categoryId: "arts",
          units: 5,
          hasLevels: false,
          levels: [],
          components: [
            { id: "int", name: "פנימי", weight: 0.50, sortOrder: 0 },
            { id: "ext", name: "בחינה חיצונית", weight: 0.50, sortOrder: 1 },
          ],
          dependsOnId: null,
          depLabel: null,
          depWeight: null,
          sortOrder: 2,
        },
        {
          id: "cinema",
          name: "קולנוע",
          categoryId: "arts",
          units: 5,
          hasLevels: false,
          levels: [],
          components: [
            { id: "int", name: "פנימי", weight: 0.50, sortOrder: 0 },
            { id: "ext", name: "בחינה חיצונית", weight: 0.50, sortOrder: 1 },
          ],
          dependsOnId: null,
          depLabel: null,
          depWeight: null,
          sortOrder: 3,
        },
      ],
    },
    {
      id: "other",
      name: "נוספים",
      icon: "\u2B50",
      sortOrder: 6,
      subjects: [
        {
          id: "pe_ext",
          name: 'חנ"ג מורחב',
          categoryId: "other",
          units: 5,
          hasLevels: false,
          levels: [],
          components: [
            { id: "ext", name: "חיצוני", weight: 0.55, sortOrder: 0 },
            { id: "int1", name: "פנימי א'", weight: 0.20, sortOrder: 1 },
            { id: "int2", name: "פנימי ב'", weight: 0.25, sortOrder: 2 },
          ],
          dependsOnId: null,
          depLabel: null,
          depWeight: null,
          sortOrder: 0,
        },
        {
          id: "toshba",
          name: 'תושב"ע',
          categoryId: "other",
          units: 5,
          hasLevels: false,
          levels: [],
          components: [
            { id: "int", name: "פנימי", weight: 0.40, sortOrder: 0 },
            { id: "ext", name: "בחינה חיצונית", weight: 0.60, sortOrder: 1 },
          ],
          dependsOnId: null,
          depLabel: null,
          depWeight: null,
          sortOrder: 1,
        },
      ],
    },
  ],
};

/**
 * Get a flat list of all subjects from a school config.
 */
export function getAllSubjects(config: SchoolConfig): import("./types").SubjectConfig[] {
  return config.categories
    .sort((a, b) => a.sortOrder - b.sortOrder)
    .flatMap((cat) =>
      [...cat.subjects].sort((a, b) => a.sortOrder - b.sortOrder)
    );
}
